sudo: false
language: python

python:
  - "2.7"
  - "pypy"
  - "3.4"

install:
  - pip install tox
  - pip install coveralls

script:
  - coverage run --source=niji tox

after_success:
  coveralls

notifications:
  email: true
