sudo: false
language: python

python:
  - "2.7"
  - "pypy"
  - "3.5"

install:
  - pip install tox
  - pip install coveralls
  - pip install pytest-cov
  - pip install -e .

script:
        - py.test --cov niji/

after_success:
  coveralls

notifications:
  email: true
