sudo: false
language: python

python:
  - "2.7"
  - "pypy"
  - "3.4"

install:
  - pip install tox
  - pip install coveralls
  - pip install pytest-cov
  - python setup.py develop

script:
        - py.test --cov niji/

after_success:
  coveralls

notifications:
  email: true
